# These are supported funding model platforms

github: # in progress!!
patreon: # in progress!!
open_collective: # need 100 stars!!
ko_fi: # https://ko-fi.com/carmzy
lfx_crowdfunding: # coming soon!!
