[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "transcribeai"
authors = [{name = "CarmZy", email = "carmzy@gphish"}]
dynamic = ["version", "description"]
